# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f306c1c802ee15e31b18e9fc8fec16bfbf69257027d74a742d5f1a65072aa3205d378be8caeb21288c5013ceac357b9e5c3d4ce8f30048b0f1b3a3f6d3dcb1

test:
  secret_key_base: a48baf2736a3002df55cd16c9e3ba011e153b2c63c897c55de77d26f3a3c9d32500160166a0d160d22f32696416ecc6de31f146a80b05cd781d91767608cf6cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
